# Base Image
FROM golang:1.23-alpine

# Habilitar CGO e instalar dependências do SQLite
ENV CGO_ENABLED=1
RUN apk update && apk add --no-cache gcc musl-dev sqlite sqlite-dev
# Configurações de ambiente
WORKDIR /app

# Copiar arquivos para o container
COPY . .

# Instalar dependências
RUN go mod tidy

# Build
RUN go build -o go-url-shortner .

# Porta exposta
EXPOSE 8080

# Comando para iniciar o servidor
CMD ["./go-url-shortner"]
